### ISSUE TITLE
ALARM SERVER: publish alarm update before calling callback

### ISSUE THREAD

**Issue by ironmig** [uf-mil/ros_alarms#29]
We noticed in testing SubjuGator that some alarms can take several seconds to raise. One reason is that the alarm server calls raise/clear callbacks registered in alarm handlers before publishing the update to the rest of the nodes connected. If this callback takes a while (such as calling a service / writing to files), this can create a significant delay in when vital nodes are notified of the change. These callbacks should either be executed async or after the update is published.

**Comment by DSsoto** [comment]
Addressed in #33, commit a79d0bf.

**Comment by whispercoros** [comment]
#33 has been merged for a while and the amonitor interface seems to have helped reduce alarm lag.

**Comment by whispercoros** [comment]
#33 has been merged for a while and the amonitor interface seems to have helped reduce alarm lag.
