### ISSUE TITLE
Python Tests

### ISSUE THREAD

**Issue by mattlangford** [uf-mil/ros_alarms#6]
Migrate current python tests into rostests

**Comment by mattlangford** [comment]
I'm having issues getting ros unit tests to work for python. I can make service calls and such but subscribers seem not to be working. I try to run [this](https://github.com/ros/ros_tutorials/blob/hydro-devel/rospy_tutorials/test/talker_listener_test.py) but even it will never find the topic. Could you try it and let me know if you can get that test to work?

**Comment by mattlangford** [comment]
Seems like subscribers in the listener never get spooled up in the tests.
I tried putting a subscriber to the `/chatter` message in the alarm listener and having it assert False whenever it get's a message but that assertion is never made when running it with the `example_support_python_node.py`

**Comment by DSsoto** [comment]
I'll take a look tomorrow.

**Comment by whispercoros** [comment]
This was addressed by @ironmig in #15.
