### ISSUE TITLE
Input Validation

### ISSUE THREAD

**Issue by DSsoto** [uf-mil/ros_alarms#7]
It would be nice if the alarm server rejected certain types of alarm names so that simple mistakes are easier to catch. For example, the empty string, possibly strings with whitespace or non-standard characters, etc.

**Comment by mattlangford** [comment]
You'd get a warning when creating the alarm, wouldn't that be good to catch any errors like that

**Comment by DSsoto** [comment]
A single line at the start of a launch is really easy to miss. Having a bit of structure as to what names are allowed also opens up the possibility for regex searches or operations in the future.

**Comment by mattlangford** [comment]
I think whitespace should be legal if the user wants to use it, and python will complain about a lot of non standard characters.
Checking for an empty string would be an easy addition though
